### ISSUE TITLE
新版报警告

### ISSUE THREAD

**Issue by ghost** [thka2016/erofsUnpack#4]
解相同的镜像
v1.3.220207有提示
v1.2.210826无异常
一个新版的截图
一个旧版的截图
![Screenshot_2022-02-08-03-20-29-30_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/40169265/152857397-f62ae143-2b4f-44f8-912d-4618ef0f2166.jpg)
![Screenshot_2022-02-08-03-20-56-67_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/40169265/152857435-665bf694-8de5-4a7a-ac77-c197bd037611.jpg)

**Comment by thka2016** [comment]
应该加了这个的原因吧？
https://github.com/thka2016/erofsUnpack/issues/3

**Comment by thka2016** [comment]
编译mkfs.erofs的时候可以把libcutils的canned_fs_config.cpp里面输出info:ignored token的那一行注释掉就可以了。
