### ISSUE TITLE
utf8error EROFS issue

### ISSUE THREAD

**Issue by lebigmac1** [thka2016/erofsUnpack#8]
Hi @thka2016
Wow! You did great job with your erofsunpackrust tool! Congratulations!
Is it okay if I use your erofs tool inside my [SystemRW / Super featuring MakeRW / ro2rw](https://github.com/lebigmac1) script? Of course I give proper credit to you sir ;)

I tried it on new Samsung device and here is the result:

```
makerw: EROFS file system detected @ vendor.img
Extracting vendor.img...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 1, error_len: Some(1) }', src/lib.rs:469:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted 
failed to find [/vendor/bin] in canned fs_config
loaded 137 fs_config entries
Creating filesystem with parameters:
    Size: 7425196032
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8096
    Inode size: 256
    Journal blocks: 0
    Label: vendor
    Blocks: 1812792
    Block groups: 56
    Reserved block group size: 447
makerw: Fatal make_ext4fs error!
```

Keep up the great work!

**Comment by thka2016** [comment]
Thank you, my tool is no longer going to be updated, but you can send me the vendor image file, and I can try to see what the problem is. fs_config and file_contexts are obtained from the image file, the specific method is written according to [erofs_utils](https://github.com/hsiangkao/erofs-utils)

**Comment by thka2016** [comment]
Files can be sent to my email thka2020@qq.com, or online disk

**Comment by lebigmac1** [comment]
https://mega.nz/file/iBgGyTLI#6Xf3VhERNAc60RxFouWruQs7WKJnnaelZpiX9ZMk4RM
Device: Samsung Galaxy S23 Ultra

Hello. Thank you for looking into it. Same error with both system.img and vendor.img, all other sub-partitions work great. I never had this problem with all my Xiaomi devices and your program works perfect on Xiaomi. Good job! Keep up the great work!

**Comment by thka2016** [comment]
You can try this [extract.erofs](https://github.com/sekaiacg/erofs-utils), which uses the relatively new erofs library

**Comment by lebigmac1** [comment]
Thank you. This issue has been resolved :)
